using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WebApplication1.Migrations
{
    /// <inheritdoc />
    public partial class AddTelegramChatIdToPatient : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE \"Patients\" ADD COLUMN IF NOT EXISTS \"Gender\" varchar(20);");
            migrationBuilder.Sql("ALTER TABLE \"Patients\" ADD COLUMN IF NOT EXISTS \"TelegramChatId\" varchar(100);");
            migrationBuilder.Sql("ALTER TABLE \"Doctors\" ADD COLUMN IF NOT EXISTS \"SpecialtyId\" integer;");
            migrationBuilder.Sql("ALTER TABLE \"AspNetUsers\" ADD COLUMN IF NOT EXISTS \"ClinicId\" uuid;");
            migrationBuilder.Sql("ALTER TABLE \"AspNetUsers\" ADD COLUMN IF NOT EXISTS \"FullName\" text;");
            migrationBuilder.Sql("ALTER TABLE \"Appointments\" ADD COLUMN IF NOT EXISTS \"DepartmentId\" integer;");
            migrationBuilder.Sql("ALTER TABLE \"Appointments\" ADD COLUMN IF NOT EXISTS \"ReferralReason\" text;");
            migrationBuilder.Sql("ALTER TABLE \"Appointments\" ADD COLUMN IF NOT EXISTS \"ReferredByDoctorId\" integer;");

            migrationBuilder.Sql(@"
DO $$ 
BEGIN
    CREATE TABLE IF NOT EXISTS ""ReferralRequests"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""ClinicId"" uuid,
        ""PatientId"" integer NOT NULL,
        ""FromDoctorId"" integer NOT NULL,
        ""TargetDepartmentId"" integer NOT NULL,
        ""TargetDoctorId"" integer,
        ""ReferralReason"" character varying(1000) NOT NULL,
        ""Urgency"" character varying(50) NOT NULL,
        ""Status"" integer NOT NULL,
        ""CreatedAt"" timestamp without time zone NOT NULL,
        CONSTRAINT ""PK_ReferralRequests"" PRIMARY KEY (""Id""),
        CONSTRAINT ""FK_ReferralRequests_Departments_TargetDepartmentId"" FOREIGN KEY (""TargetDepartmentId"") REFERENCES ""Departments"" (""DepartmentId"") ON DELETE RESTRICT,
        CONSTRAINT ""FK_ReferralRequests_Doctors_FromDoctorId"" FOREIGN KEY (""FromDoctorId"") REFERENCES ""Doctors"" (""DoctorId"") ON DELETE RESTRICT,
        CONSTRAINT ""FK_ReferralRequests_Doctors_TargetDoctorId"" FOREIGN KEY (""TargetDoctorId"") REFERENCES ""Doctors"" (""DoctorId"") ON DELETE SET NULL,
        CONSTRAINT ""FK_ReferralRequests_Patients_PatientId"" FOREIGN KEY (""PatientId"") REFERENCES ""Patients"" (""PatientId"") ON DELETE CASCADE
    );
EXCEPTION WHEN duplicate_table THEN NULL; WHEN duplicate_object THEN NULL;
END $$;");

            migrationBuilder.Sql(@"
DO $$ 
BEGIN
    CREATE TABLE IF NOT EXISTS ""Specialties"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""ClinicId"" uuid,
        ""Name"" character varying(150) NOT NULL,
        ""Description"" character varying(500),
        ""DepartmentId"" integer NOT NULL,
        CONSTRAINT ""PK_Specialties"" PRIMARY KEY (""Id""),
        CONSTRAINT ""FK_Specialties_Departments_DepartmentId"" FOREIGN KEY (""DepartmentId"") REFERENCES ""Departments"" (""DepartmentId"") ON DELETE CASCADE
    );
EXCEPTION WHEN duplicate_table THEN NULL; WHEN duplicate_object THEN NULL;
END $$;");

            migrationBuilder.Sql(@"
DO $$ 
BEGIN
    CREATE TABLE IF NOT EXISTS ""Notifications"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""ClinicId"" uuid,
        ""Title"" character varying(200) NOT NULL,
        ""Message"" character varying(1000) NOT NULL,
        ""Type"" character varying(50) NOT NULL,
        ""TargetRole"" character varying(50) NOT NULL,
        ""PatientId"" integer,
        ""ReferralRequestId"" integer,
        ""AppointmentId"" integer,
        ""DoctorName"" character varying(150),
        ""PatientName"" character varying(150),
        ""DepartmentName"" character varying(150),
        ""IsRead"" boolean NOT NULL,
        ""CreatedAt"" timestamp without time zone NOT NULL,
        CONSTRAINT ""PK_Notifications"" PRIMARY KEY (""Id""),
        CONSTRAINT ""FK_Notifications_Appointments_AppointmentId"" FOREIGN KEY (""AppointmentId"") REFERENCES ""Appointments"" (""AppointmentId"") ON DELETE CASCADE,
        CONSTRAINT ""FK_Notifications_Patients_PatientId"" FOREIGN KEY (""PatientId"") REFERENCES ""Patients"" (""PatientId"") ON DELETE CASCADE,
        CONSTRAINT ""FK_Notifications_ReferralRequests_ReferralRequestId"" FOREIGN KEY (""ReferralRequestId"") REFERENCES ""ReferralRequests"" (""Id"") ON DELETE CASCADE
    );
EXCEPTION WHEN duplicate_table THEN NULL; WHEN duplicate_object THEN NULL;
END $$;");

            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Doctors_SpecialtyId"" ON ""Doctors"" (""SpecialtyId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_AspNetUsers_ClinicId"" ON ""AspNetUsers"" (""ClinicId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Appointments_DepartmentId"" ON ""Appointments"" (""DepartmentId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Appointments_ReferredByDoctorId"" ON ""Appointments"" (""ReferredByDoctorId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Notifications_AppointmentId"" ON ""Notifications"" (""AppointmentId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Notifications_ClinicId"" ON ""Notifications"" (""ClinicId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Notifications_CreatedAt"" ON ""Notifications"" (""CreatedAt"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Notifications_IsRead"" ON ""Notifications"" (""IsRead"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Notifications_PatientId"" ON ""Notifications"" (""PatientId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Notifications_ReferralRequestId"" ON ""Notifications"" (""ReferralRequestId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_ReferralRequests_ClinicId"" ON ""ReferralRequests"" (""ClinicId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_ReferralRequests_FromDoctorId"" ON ""ReferralRequests"" (""FromDoctorId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_ReferralRequests_PatientId"" ON ""ReferralRequests"" (""PatientId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_ReferralRequests_Status"" ON ""ReferralRequests"" (""Status"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_ReferralRequests_TargetDepartmentId"" ON ""ReferralRequests"" (""TargetDepartmentId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_ReferralRequests_TargetDoctorId"" ON ""ReferralRequests"" (""TargetDoctorId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Specialties_DepartmentId"" ON ""Specialties"" (""DepartmentId"");");

            migrationBuilder.Sql(@"
DO $$ BEGIN
    ALTER TABLE ""Appointments"" ADD CONSTRAINT ""FK_Appointments_Departments_DepartmentId"" FOREIGN KEY (""DepartmentId"") REFERENCES ""Departments"" (""DepartmentId"") ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;");

            migrationBuilder.Sql(@"
DO $$ BEGIN
    ALTER TABLE ""Appointments"" ADD CONSTRAINT ""FK_Appointments_Doctors_ReferredByDoctorId"" FOREIGN KEY (""ReferredByDoctorId"") REFERENCES ""Doctors"" (""DoctorId"") ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;");

            migrationBuilder.Sql(@"
DO $$ BEGIN
    ALTER TABLE ""Doctors"" ADD CONSTRAINT ""FK_Doctors_Specialties_SpecialtyId"" FOREIGN KEY (""SpecialtyId"") REFERENCES ""Specialties"" (""Id"") ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Appointments_Departments_DepartmentId",
                table: "Appointments");

            migrationBuilder.DropForeignKey(
                name: "FK_Appointments_Doctors_ReferredByDoctorId",
                table: "Appointments");

            migrationBuilder.DropForeignKey(
                name: "FK_Doctors_Specialties_SpecialtyId",
                table: "Doctors");

            migrationBuilder.DropTable(
                name: "Notifications");

            migrationBuilder.DropTable(
                name: "Specialties");

            migrationBuilder.DropTable(
                name: "ReferralRequests");

            migrationBuilder.DropIndex(
                name: "IX_Doctors_SpecialtyId",
                table: "Doctors");

            migrationBuilder.DropIndex(
                name: "IX_AspNetUsers_ClinicId",
                table: "AspNetUsers");

            migrationBuilder.DropIndex(
                name: "IX_Appointments_DepartmentId",
                table: "Appointments");

            migrationBuilder.DropIndex(
                name: "IX_Appointments_ReferredByDoctorId",
                table: "Appointments");

            migrationBuilder.DropColumn(
                name: "Gender",
                table: "Patients");

            migrationBuilder.DropColumn(
                name: "TelegramChatId",
                table: "Patients");

            migrationBuilder.DropColumn(
                name: "SpecialtyId",
                table: "Doctors");

            migrationBuilder.DropColumn(
                name: "ClinicId",
                table: "AspNetUsers");

            migrationBuilder.DropColumn(
                name: "FullName",
                table: "AspNetUsers");

            migrationBuilder.DropColumn(
                name: "DepartmentId",
                table: "Appointments");

            migrationBuilder.DropColumn(
                name: "ReferralReason",
                table: "Appointments");

            migrationBuilder.DropColumn(
                name: "ReferredByDoctorId",
                table: "Appointments");
        }
    }
}
